import type { BarrelRaidNotificationRepository } from "../db/repositories/barrelRaidNotificationRepository";
import type { ActivityEventService } from "../services/activityEventService";
import type { AchievementService } from "../services/achievementService";
import type { AdventureService } from "../services/adventureService";
import type { BardPerformanceService } from "../services/bardPerformanceService";
import type { BarrelBeerTutorialService } from "../services/barrelBeerTutorialService";
import type { CellarErrandService } from "../services/cellarErrandService";
import type { CellarGrownupQuestService } from "../services/cellarGrownupQuestService";
import type { ClassNoncombatService } from "../services/classNoncombatService";
import type { DevGrantService } from "../services/devGrantService";
import type { DevResetService } from "../services/devResetService";
import type { DailyKorchmaRoundService } from "../services/dailyKorchmaRoundService";
import type { DuelChallengeService } from "../services/duelChallengeService";
import type { DuelTournamentService } from "../services/duelTournamentService";
import type { EquipmentService } from "../services/equipmentService";
import type { FightService } from "../services/fightService";
import type { FirstKorchmaQuestService } from "../services/firstKorchmaQuestService";
import type { FightingCornerQuestService } from "../services/fightingCornerQuestService";
import type { HeroService } from "../services/heroService";
import type { HealthRecoveryNotificationService } from "../services/healthRecoveryNotificationService";
import type { HuntService } from "../services/huntService";
import type { InventoryService } from "../services/inventoryService";
import type { ItemCraftService } from "../services/itemCraftService";
import type { ItemUpgradeService } from "../services/itemUpgradeService";
import type { ItemUseService } from "../services/itemUseService";
import type { ItemTransferService } from "../services/itemTransferService";
import type { LevelBarterService } from "../services/levelBarterService";
import type { LevelMilestoneService } from "../services/levelMilestoneService";
import type { MantokChestService } from "../services/mantokChestService";
import type { OnboardingService } from "../services/onboardingService";
import type { PassageSearchService } from "../services/passageSearchService";
import type { PartyBossService } from "../services/partyBossService";
import type { PartyRaidChatService } from "../services/partyRaidChatService";
import type { PartySessionService } from "../services/partySessionService";
import type { PlayerHintService } from "../services/playerHintService";
import type { PresenceService } from "../services/presenceService";
import type { RemortService } from "../services/remortService";
import type { RestartService } from "../services/restartService";
import type { ShynokService } from "../services/shynokService";
import type { TavernGameService } from "../services/tavernGameService";
import type { TavernRaidService } from "../services/tavernRaidService";
import type { TrainingDoppelgangerService } from "../services/trainingDoppelgangerService";
import type { YegerQuestService } from "../services/yegerQuestService";

export interface BotServices {
  activityEvents: ActivityEventService;
  achievements: AchievementService;
  adventure: AdventureService;
  bardPerformance?: BardPerformanceService;
  barrelBeerTutorial: BarrelBeerTutorialService;
  barrelRaidNotifications?: BarrelRaidNotificationRepository;
  cellarErrand: CellarErrandService;
  cellarGrownup?: CellarGrownupQuestService;
  classNoncombat?: ClassNoncombatService;
  dailyKorchmaRound: DailyKorchmaRoundService;
  fight: FightService;
  firstKorchmaQuest: FirstKorchmaQuestService;
  fightingCornerQuest: FightingCornerQuestService;
  hunt: HuntService;
  yeger: YegerQuestService;
  onboarding: OnboardingService;
  passageSearch?: PassageSearchService;
  partyBoss?: PartyBossService;
  partyRaidChat?: PartyRaidChatService;
  partySessions?: PartySessionService;
  playerHints: PlayerHintService;
  hero: HeroService;
  healthRecoveryNotifications?: HealthRecoveryNotificationService;
  equipment: EquipmentService;
  inventory: InventoryService;
  itemCraft: ItemCraftService;
  itemUpgrades: ItemUpgradeService;
  itemUse: ItemUseService;
  itemTransfers?: ItemTransferService;
  levelBarter: LevelBarterService;
  levelMilestones?: LevelMilestoneService;
  mantokChest: MantokChestService;
  shynok?: ShynokService;
  tavernGames?: TavernGameService;
  presence: PresenceService;
  devGrant?: DevGrantService;
  duel?: DuelChallengeService;
  duelTournaments?: DuelTournamentService;
  devReset: DevResetService;
  restart: RestartService;
  remort?: RemortService;
  tavern: TavernRaidService;
  trainingDoppelganger?: TrainingDoppelgangerService;
}
